from typing import Any


class Model:
    def __init__(
        self,
        model_path: str | None = ...,
        model_name: str | None = ...,
        lang: str | None = ...
    ) -> None: ...


class KaldiRecognizer:
    def __init__(self, *args: Any) -> None: ...
    def AcceptWaveform(self, data: bytes) -> bool: ...
    def Result(self) -> str: ...
    def PartialResult(self) -> str: ...
